### ISSUE TITLE
Warning: count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/custom_search#1]
Getting this error with PHP 7.x:

> Warning: count(): Parameter must be an array or an object that implements Countable in custom_search_preprocess_search_results() (line 37 of /app/modules/contrib/custom_search/templates/custom_search.pages.inc).

The code should check first if it's an array or an object before trying to count. This might have been fixed in the D7 version.

**Comment by herbdool** [comment]
I've got a PR to fix this specific issue by making sure the variable is an array.

But there might be a different problem here as well. This undefined variable is because `current_node_types` isn't set in config. But that's not set because a search block hasn't been configured. But it seems that the code doesn't take into account that a block can be added multiple times to layouts so instead of just checking `current_node_types` it should be doing this for each block instance. I'll create a new issue.

**Comment by argiepiano** [comment]
I'm having a hard time reproducing this error. Can you give me some steps, so that I can test the PR?

**Comment by herbdool** [comment]
Using PHP 8. This was for a particular client site but I believe it would often return NULL since `current_node_types` isn't in the default config file. If it's missing then it returns NULL.

**Comment by argiepiano** [comment]
After many trials I was able to reproduce. It's a rather unusual situation. For the record:
1. Enable Custom Search
2. Visit the config page at `admin/config/search/custom_search` and set Position to either above or below the results. Save
3.  Visit the main Search page at `/search/node` (do not use a Custom Search block)
4. Search by any criteria 

The error is produced because, if you do a search through the main search page, without having used the search form shown inside the Custom Search block, the `current_node_types` key for `custom_search.settings.json` is never set. 

This key is only set by `custom_search_submit()`, which is a custom submit handler used by the form inside the Custom Search block. This submit handler is never invoked if you use the main search page without first having performed a search through the block's form. 

There may some logic error in this process, but I don't have the time to debug or investigate. Apparently this error was introduced when the module was adapted to Backdrop's block system. 

So, the PR submitted here is in a way a "patch" for other logical problems in the module. Regardless of that, I think it's fine to merge (I do have a small additional comment, which I'll add to the PR)

**Comment by herbdool** [comment]
Only noticed your approval now @argiepiano. I've merged on behalf of the @backdrop-contrib/bug-squad
